//***************************************************************************
//	File:                       PizzaCalculator.Java
//
//	Student:                    Chris Stahle
//
//	Assignment:                 Program  # Extra Credit
//
//	Course Name:                Java Programming I
//
//	Course Number:              COSC 2050 - 01
//
//      Due:                        October 4, 2016
//
//      Description:                
//                                   
//***************************************************************************

package UI;

public class PizzaCalculatorForm extends javax.swing.JFrame {
    double sum = 0.0;
    
    double small=6.99;
    double medium=8.99;
    double large=10.99;
    
    double sausage=1.49;
    double pepperoni=1.49;
    double salami=1.49;
    double olives=0.99;
    double mushrooms=0.99;
    double anchovies=0.99;

    public PizzaCalculatorForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        sizeButtonPanel = new javax.swing.JPanel();
        smallButton = new javax.swing.JRadioButton();
        mediumButton = new javax.swing.JRadioButton();
        largeButton = new javax.swing.JRadioButton();
        toppingsPanel = new javax.swing.JPanel();
        sausageCheckbox = new javax.swing.JCheckBox();
        pepperoniCheckbox = new javax.swing.JCheckBox();
        salamiCheckbox = new javax.swing.JCheckBox();
        anchoviesCheckbox = new javax.swing.JCheckBox();
        mushroomsCheckbox = new javax.swing.JCheckBox();
        olivesCheckbox = new javax.swing.JCheckBox();
        priceLabel = new javax.swing.JLabel();
        priceTextField = new javax.swing.JTextField();
        calculateButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sizeButtonPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Size"));
        sizeButtonPanel.setToolTipText("");

        buttonGroup1.add(smallButton);
        smallButton.setText("Small");
        smallButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smallButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(mediumButton);
        mediumButton.setText("Medium");
        mediumButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mediumButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(largeButton);
        largeButton.setText("Large");
        largeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                largeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sizeButtonPanelLayout = new javax.swing.GroupLayout(sizeButtonPanel);
        sizeButtonPanel.setLayout(sizeButtonPanelLayout);
        sizeButtonPanelLayout.setHorizontalGroup(
            sizeButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sizeButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(smallButton)
                .addGap(33, 33, 33)
                .addComponent(mediumButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(largeButton)
                .addGap(31, 31, 31))
        );
        sizeButtonPanelLayout.setVerticalGroup(
            sizeButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sizeButtonPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(sizeButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(smallButton)
                    .addComponent(mediumButton)
                    .addComponent(largeButton))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        toppingsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Toppings"));

        sausageCheckbox.setText("Sausage");
        sausageCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sausageCheckboxActionPerformed(evt);
            }
        });

        pepperoniCheckbox.setText("Pepperoni");
        pepperoniCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pepperoniCheckboxActionPerformed(evt);
            }
        });

        salamiCheckbox.setText("Salami");
        salamiCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salamiCheckboxActionPerformed(evt);
            }
        });

        anchoviesCheckbox.setText("Anchovies");
        anchoviesCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anchoviesCheckboxActionPerformed(evt);
            }
        });

        mushroomsCheckbox.setText("Mushrooms");
        mushroomsCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mushroomsCheckboxActionPerformed(evt);
            }
        });

        olivesCheckbox.setText("Olives");
        olivesCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                olivesCheckboxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout toppingsPanelLayout = new javax.swing.GroupLayout(toppingsPanel);
        toppingsPanel.setLayout(toppingsPanelLayout);
        toppingsPanelLayout.setHorizontalGroup(
            toppingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toppingsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(toppingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pepperoniCheckbox)
                    .addComponent(salamiCheckbox)
                    .addComponent(sausageCheckbox))
                .addGap(55, 55, 55)
                .addGroup(toppingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(mushroomsCheckbox)
                    .addComponent(olivesCheckbox, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(anchoviesCheckbox, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        toppingsPanelLayout.setVerticalGroup(
            toppingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toppingsPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(toppingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sausageCheckbox)
                    .addComponent(olivesCheckbox))
                .addGap(18, 18, 18)
                .addGroup(toppingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pepperoniCheckbox)
                    .addComponent(mushroomsCheckbox))
                .addGap(18, 18, 18)
                .addGroup(toppingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salamiCheckbox)
                    .addComponent(anchoviesCheckbox))
                .addGap(25, 25, 25))
        );

        priceLabel.setText("Price:");

        priceTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceTextFieldActionPerformed(evt);
            }
        });

        calculateButton.setText("Calculate");
        calculateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateButtonActionPerformed(evt);
            }
        });

        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(calculateButton)
                        .addGap(18, 18, 18)
                        .addComponent(exitButton))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sizeButtonPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(priceLabel)
                                .addGap(18, 18, 18)
                                .addComponent(priceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(clearButton)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(toppingsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sizeButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(toppingsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priceLabel)
                    .addComponent(priceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calculateButton)
                    .addComponent(exitButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void smallButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smallButtonActionPerformed
       //if the small button is selected without any other button being selected..
        if(smallButton.isSelected())
            sum += small;
        else
            sum-= small;
        //if the small button is selected while the medium button is selected..
        if(mediumButton.isSelected())
        {
            sum -= medium;
            mediumButton.setSelected(false);
        }
        //if the small button is selected while the large button is selected...
        else if(largeButton.isSelected())
        {
            sum -= large;
            largeButton.setSelected(false);
        }
    }//GEN-LAST:event_smallButtonActionPerformed

    private void calculateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateButtonActionPerformed
        int temp =(int) (sum*100);
        sum =temp/100.0;
        priceTextField.setText(String.valueOf(sum));
        
        
    }//GEN-LAST:event_calculateButtonActionPerformed

    private void largeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_largeButtonActionPerformed
        if(largeButton.isSelected()) //3
            sum += large;
        else
            sum -= large;
        //if the large button is selected while the small button is selected..
        if(smallButton.isSelected()) //1
        {
            sum -= small;
            smallButton.setSelected(false);
        }
        //if the large button is selected while the medium button is selected...
        else if(mediumButton.isSelected()) //2
        {
            sum -= medium;
            mediumButton.setSelected(false);
        }
    }//GEN-LAST:event_largeButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        System.exit(0);   
    }//GEN-LAST:event_exitButtonActionPerformed

    private void priceTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceTextFieldActionPerformed

    private void sausageCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sausageCheckboxActionPerformed
        if(sausageCheckbox.isSelected())
            sum += sausage;
        else
            sum -= sausage;
    }//GEN-LAST:event_sausageCheckboxActionPerformed

    private void olivesCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_olivesCheckboxActionPerformed
        if(olivesCheckbox.isSelected())
            sum += olives;
        else
            sum -= olives;
    }//GEN-LAST:event_olivesCheckboxActionPerformed

    private void pepperoniCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pepperoniCheckboxActionPerformed
        if(pepperoniCheckbox.isSelected())
            sum += pepperoni;
        else
            sum -= pepperoni;
    }//GEN-LAST:event_pepperoniCheckboxActionPerformed

    private void mushroomsCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mushroomsCheckboxActionPerformed
        if(mushroomsCheckbox.isSelected())
            sum += mushrooms;
        else
            sum -= mushrooms;
    }//GEN-LAST:event_mushroomsCheckboxActionPerformed

    private void salamiCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salamiCheckboxActionPerformed
        if(salamiCheckbox.isSelected())
            sum += salami;
        else
            sum -= salami;
    }//GEN-LAST:event_salamiCheckboxActionPerformed

    private void anchoviesCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anchoviesCheckboxActionPerformed
        if(anchoviesCheckbox.isSelected())
            sum += anchovies;
        else
            sum -= anchovies;
    }//GEN-LAST:event_anchoviesCheckboxActionPerformed

    private void mediumButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mediumButtonActionPerformed
        if(mediumButton.isSelected()) //2
            sum += medium;
        else
            sum -= medium;
        //if the medium button is selected while the small button is selected..
        if(smallButton.isSelected()) //1
        {
            sum -= medium;
            smallButton.setSelected(false);
        }
        //if the medium button is selected while the large button is selected...
        else if(largeButton.isSelected()) //3
        {
            sum -= large;
            largeButton.setSelected(false);
        }
    }//GEN-LAST:event_mediumButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        sausageCheckbox.setSelected(false);
        olivesCheckbox.setSelected(false);
        pepperoniCheckbox.setSelected(false);
        mushroomsCheckbox.setSelected(false);
        salamiCheckbox.setSelected(false);
        anchoviesCheckbox.setSelected(false);
        /////////////////////////////////////
        buttonGroup1.clearSelection();//just found out about this...adding it in
        ////////////////////////////////////
        sum = 0.0;
        priceTextField.setText("");
    }//GEN-LAST:event_clearButtonActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PizzaCalculatorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PizzaCalculatorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PizzaCalculatorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PizzaCalculatorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new PizzaCalculatorForm().setVisible(true);
                                //new ValidatorTestFrame().setVisible(true);
                PizzaCalculatorForm frame = new PizzaCalculatorForm ();
                frame.setVisible(true);
                frame.setLocationRelativeTo(null); //center the frame 
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox anchoviesCheckbox;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton calculateButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JRadioButton largeButton;
    private javax.swing.JRadioButton mediumButton;
    private javax.swing.JCheckBox mushroomsCheckbox;
    private javax.swing.JCheckBox olivesCheckbox;
    private javax.swing.JCheckBox pepperoniCheckbox;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JTextField priceTextField;
    private javax.swing.JCheckBox salamiCheckbox;
    private javax.swing.JCheckBox sausageCheckbox;
    private javax.swing.JPanel sizeButtonPanel;
    private javax.swing.JRadioButton smallButton;
    private javax.swing.JPanel toppingsPanel;
    // End of variables declaration//GEN-END:variables
}
