//***************************************************************************
//	File:                       Lineup.Java
//
//	Student:                    Chris Stahle
//
//	Assignment:                 Program  # 7
//
//	Course Name:                Java Programming I
//
//	Course Number:              COSC 2050 - 01
//
//      Due:                        October 11, 2016
//
//      Description:                This GUI program allows users to enter
//                                  names and assign those names to a baseball 
//                                  position.
//***************************************************************************

package UI;

import Utilities.Validator;
import java.awt.Color;
import javax.swing.JRadioButton;

/**
 *
 * @author stahl
 */
public class LineupFrame extends javax.swing.JFrame {

    public LineupFrame() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        oneTextField = new javax.swing.JTextField();
        teamInformationPanel = new javax.swing.JPanel();
        teamNameTextField = new javax.swing.JTextField();
        teamNameLabel = new javax.swing.JLabel();
        homeButton = new javax.swing.JRadioButton();
        visitorButton = new javax.swing.JRadioButton();
        oneLabel = new javax.swing.JLabel();
        twoLabel = new javax.swing.JLabel();
        threeLabel = new javax.swing.JLabel();
        fourLabel = new javax.swing.JLabel();
        sevenLabel = new javax.swing.JLabel();
        eightLabel = new javax.swing.JLabel();
        sixLabel = new javax.swing.JLabel();
        fiveLabel = new javax.swing.JLabel();
        nineLabel = new javax.swing.JLabel();
        twoTextField = new javax.swing.JTextField();
        threeTextField = new javax.swing.JTextField();
        fourTextField = new javax.swing.JTextField();
        sevenTextField = new javax.swing.JTextField();
        eightTextField = new javax.swing.JTextField();
        sixTextField = new javax.swing.JTextField();
        fiveTextField = new javax.swing.JTextField();
        nineTextField = new javax.swing.JTextField();
        oneComboBox = new javax.swing.JComboBox<>();
        twoComboBox = new javax.swing.JComboBox<>();
        fourComboBox = new javax.swing.JComboBox<>();
        threeComboBox = new javax.swing.JComboBox<>();
        fiveComboBox = new javax.swing.JComboBox<>();
        sixComboBox = new javax.swing.JComboBox<>();
        sevenComboBox = new javax.swing.JComboBox<>();
        eightComboBox = new javax.swing.JComboBox<>();
        nineComboBox = new javax.swing.JComboBox<>();
        okButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lineup");

        oneTextField.setForeground(new java.awt.Color(204, 204, 204));
        oneTextField.setText("H. Perkins");
        oneTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                oneTextFieldFocusGained(evt);
            }
        });
        oneTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneTextFieldActionPerformed(evt);
            }
        });

        teamInformationPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Team Information"));

        teamNameTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                teamNameTextFieldFocusGained(evt);
            }
        });
        teamNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teamNameTextFieldActionPerformed(evt);
            }
        });

        teamNameLabel.setText("Team Name:  ");

        buttonGroup1.add(homeButton);
        homeButton.setText("Home");

        buttonGroup1.add(visitorButton);
        visitorButton.setText("Visitor");

        javax.swing.GroupLayout teamInformationPanelLayout = new javax.swing.GroupLayout(teamInformationPanel);
        teamInformationPanel.setLayout(teamInformationPanelLayout);
        teamInformationPanelLayout.setHorizontalGroup(
            teamInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(teamInformationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(teamNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(teamNameTextField)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(homeButton)
                .addGap(10, 10, 10)
                .addComponent(visitorButton)
                .addContainerGap())
        );
        teamInformationPanelLayout.setVerticalGroup(
            teamInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, teamInformationPanelLayout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(teamInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teamNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teamNameLabel)
                    .addComponent(homeButton)
                    .addComponent(visitorButton))
                .addContainerGap())
        );

        oneLabel.setText("1.");

        twoLabel.setText("2.");

        threeLabel.setText("3.");

        fourLabel.setText("4.");

        sevenLabel.setText("7.");

        eightLabel.setText("8.");

        sixLabel.setText("6.");

        fiveLabel.setText("5.");

        nineLabel.setText("9.");

        twoTextField.setForeground(new java.awt.Color(204, 204, 204));
        twoTextField.setText("C.Cousins");
        twoTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                twoTextFieldFocusGained(evt);
            }
        });
        twoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoTextFieldActionPerformed(evt);
            }
        });

        threeTextField.setForeground(new java.awt.Color(204, 204, 204));
        threeTextField.setText("Etc...");

        oneComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose a selection", "Pitcher", "Catcher", "First base", "Second base", "Third base", "Short stop", "Left field", "Center field", "Right field" }));
        oneComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneComboBoxActionPerformed(evt);
            }
        });

        twoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose a selection", "Pitcher", "Catcher", "First base", "Second base", "Third base", "Short stop", "Left field", "Center field", "Right field" }));
        twoComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoComboBoxActionPerformed(evt);
            }
        });

        fourComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose a selection", "Pitcher", "Catcher", "First base", "Second base", "Third base", "Short stop", "Left field", "Center field", "Right field" }));
        fourComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourComboBoxActionPerformed(evt);
            }
        });

        threeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose a selection", "Pitcher", "Catcher", "First base", "Second base", "Third base", "Short stop", "Left field", "Center field", "Right field" }));
        threeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeComboBoxActionPerformed(evt);
            }
        });

        fiveComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose a selection", "Pitcher", "Catcher", "First base", "Second base", "Third base", "Short stop", "Left field", "Center field", "Right field" }));
        fiveComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveComboBoxActionPerformed(evt);
            }
        });

        sixComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose a selection", "Pitcher", "Catcher", "First base", "Second base", "Third base", "Short stop", "Left field", "Center field", "Right field" }));
        sixComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixComboBoxActionPerformed(evt);
            }
        });

        sevenComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose a selection", "Pitcher", "Catcher", "First base", "Second base", "Third base", "Short stop", "Left field", "Center field", "Right field" }));
        sevenComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevenComboBoxActionPerformed(evt);
            }
        });

        eightComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose a selection", "Pitcher", "Catcher", "First base", "Second base", "Third base", "Short stop", "Left field", "Center field", "Right field" }));
        eightComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eightComboBoxActionPerformed(evt);
            }
        });

        nineComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose a selection", "Pitcher", "Catcher", "First base", "Second base", "Third base", "Short stop", "Left field", "Center field", "Right field" }));
        nineComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nineComboBoxActionPerformed(evt);
            }
        });

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(teamInformationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(twoLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(twoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(twoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fourLabel)
                                    .addComponent(threeLabel)
                                    .addComponent(fiveLabel)
                                    .addComponent(sevenLabel)
                                    .addComponent(sixLabel)
                                    .addComponent(eightLabel)
                                    .addComponent(nineLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(nineTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(nineComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(threeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(fourTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(fourComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(threeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(sixTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(eightTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(sevenTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(fiveTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(sixComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(eightComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(sevenComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(fiveComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(clearButton)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(oneLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(oneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(oneComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 41, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(okButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(exitButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(teamInformationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oneLabel)
                    .addComponent(oneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(oneComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(twoLabel)
                    .addComponent(twoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(twoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(threeLabel)
                            .addComponent(threeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fourLabel)
                            .addComponent(fourTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(threeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fourComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fiveLabel)
                            .addComponent(fiveTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sixLabel)
                            .addComponent(sixTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sevenLabel)
                            .addComponent(sevenTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(eightLabel)
                            .addComponent(eightTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fiveComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sixComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sevenComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(eightComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nineLabel)
                    .addComponent(nineTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nineComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButton)
                    .addComponent(exitButton)
                    .addComponent(clearButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed
    private boolean isValidData() 
    {
        Validator v = new Validator();
        //everything is present
        //all names are non numeric, team name is whatever u want
        //is the position assigned already
        //is the player assigned already
        //! they can enter the name however they want bc it's their experience,
        //they dont have to enter "C. Stahle", validation for that is annoying
        return v.isPresent(teamNameTextField, "Team name ") &&
               v.isAButtonSelected(homeButton, visitorButton, "Home or Visitor ") &&
                
               v.isPresent(oneTextField, "player 1 ") &&
               v.isFormattedName(oneTextField, "player 1's name ") &&
               v.isComboBoxSet(oneComboBox, "player 1's position ") &&
                
               v.isPresent(twoTextField, "player 2 ") && 
               v.isFormattedName(twoTextField, "player 2's name ") &&
               v.isComboBoxSet(twoComboBox, "player 2's position ") && 
               v.isTheSamePositionAlreadyAssigned(oneComboBox, twoComboBox) && 
               v.isTheSamePlayerAlreadyAssigned(oneTextField, twoTextField) && 
                
               v.isPresent(threeTextField, "player 3 ") &&
               v.isFormattedName(threeTextField, "player 3's name ") && 
               v.isComboBoxSet(threeComboBox, "player 3's position ") &&
               v.isTheSamePositionAlreadyAssigned(twoComboBox, threeComboBox) &&
               v.isTheSamePlayerAlreadyAssigned(twoTextField, threeTextField) &&
                
               v.isPresent(fourTextField, "player 4 ") &&
               v.isFormattedName(fourTextField, "player 4's name ") &&
               v.isComboBoxSet(fourComboBox, "player 4's position ") && 
               v.isTheSamePositionAlreadyAssigned(threeComboBox, fourComboBox) &&  
               v.isTheSamePlayerAlreadyAssigned(threeTextField, fourTextField) && 
                
               v.isPresent(fiveTextField, "player 5 ") &&
               v.isFormattedName(fiveTextField, "player 5's name ") &&
               v.isComboBoxSet(fiveComboBox, "player 5's position ") && 
               v.isTheSamePositionAlreadyAssigned(fourComboBox, fiveComboBox) && 
               v.isTheSamePlayerAlreadyAssigned(fourTextField, fiveTextField) && 
                
               v.isPresent(sixTextField, "player 6 ") && 
               v.isFormattedName(sixTextField, "player 6's name ") &&
               v.isComboBoxSet(sixComboBox, "player 6's position ") && 
               v.isTheSamePositionAlreadyAssigned(fiveComboBox, sixComboBox) && 
               v.isTheSamePlayerAlreadyAssigned(fiveTextField, sixTextField) && 
                
               v.isPresent(sevenTextField,"player 7 ") &&
               v.isFormattedName(sevenTextField, "player 7's name ") && 
               v.isComboBoxSet(sevenComboBox, "player 7's position ") &&
               v.isTheSamePositionAlreadyAssigned(sixComboBox, sevenComboBox) && 
               v.isTheSamePlayerAlreadyAssigned(sixTextField, sevenTextField) && 
                
               v.isPresent(eightTextField, "player 8 ") &&
               v.isFormattedName(eightTextField, "player 8's name ") && 
               v.isComboBoxSet(eightComboBox, "player 8's position ") &&
               v.isTheSamePositionAlreadyAssigned(sevenComboBox, eightComboBox) &&
               v.isTheSamePlayerAlreadyAssigned(sevenTextField, eightTextField) && 
                
               v.isPresent(nineTextField, "player 9 ") &&
               v.isFormattedName(nineTextField, "player 9's name ") && 
               v.isComboBoxSet(nineComboBox, "player 9's position ") &&
               v.isTheSamePositionAlreadyAssigned(eightComboBox, nineComboBox) && 
               v.isTheSamePlayerAlreadyAssigned(eightTextField, nineTextField);
    }
    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        if(isValidData() )
        {
            System.out.print(
        teamNameTextField.getText() + getTheSelectedButton(homeButton, visitorButton) + 
        oneTextField.getText() + ", " + oneComboBox.getSelectedItem() + "\n" + 
        twoTextField.getText() + ", " + twoComboBox.getSelectedItem() + "\n" + 
        threeTextField.getText() + ", " + threeComboBox.getSelectedItem() + "\n" + 
        fourTextField.getText() + ", " + fourComboBox.getSelectedItem() + "\n" + 
        fiveTextField.getText() + ", " + fiveComboBox.getSelectedItem() + "\n" + 
        sixTextField.getText() + ", " + sixComboBox.getSelectedItem() + "\n" + 
        sevenTextField.getText() + ", " + sevenComboBox.getSelectedItem() + "\n" + 
        eightTextField.getText() + ", " + eightComboBox.getSelectedItem() + "\n" + 
        nineTextField.getText() + ", " +  nineComboBox.getSelectedItem() + "\n");
        }
        // System.out.print(formatter(all the text fields))
    }//GEN-LAST:event_okButtonActionPerformed
    private String getTheSelectedButton(JRadioButton h, JRadioButton v)
    {
        if(h.isSelected())
            return "(" + h.getText() + " team)\n\n"; 
        return "(" + v.getText() + "'s team)\n\n";
    }
    private void oneComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneComboBoxActionPerformed
        
    }//GEN-LAST:event_oneComboBoxActionPerformed

    private void twoComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoComboBoxActionPerformed
    }//GEN-LAST:event_twoComboBoxActionPerformed

    private void threeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeComboBoxActionPerformed
    }//GEN-LAST:event_threeComboBoxActionPerformed

    private void fourComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourComboBoxActionPerformed
    }//GEN-LAST:event_fourComboBoxActionPerformed

    private void fiveComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveComboBoxActionPerformed
    }//GEN-LAST:event_fiveComboBoxActionPerformed

    private void sixComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixComboBoxActionPerformed
    }//GEN-LAST:event_sixComboBoxActionPerformed

    private void sevenComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevenComboBoxActionPerformed
    }//GEN-LAST:event_sevenComboBoxActionPerformed

    private void eightComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eightComboBoxActionPerformed
    }//GEN-LAST:event_eightComboBoxActionPerformed

    private void nineComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nineComboBoxActionPerformed
        //String ninesItemText = (String)oneComboBox.getSelectedItem();
    }//GEN-LAST:event_nineComboBoxActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        //reset buttons\\
        buttonGroup1.clearSelection(); 
        //reset comboBoxes to default\\
        oneComboBox.setSelectedIndex(0);
        twoComboBox.setSelectedIndex(0);
        threeComboBox.setSelectedIndex(0);
        fourComboBox.setSelectedIndex(0);
        fiveComboBox.setSelectedIndex(0);
        sixComboBox.setSelectedIndex(0);
        sevenComboBox.setSelectedIndex(0);
        eightComboBox.setSelectedIndex(0);
        nineComboBox.setSelectedIndex(0);
        //reset textFields\\
        oneTextField.setText("");
        twoTextField.setText("");
        threeTextField.setText("");
        fourTextField.setText("");
        fiveTextField.setText("");
        sixTextField.setText("");
        sevenTextField.setText("");
        eightTextField.setText("");
        nineTextField.setText("");
        //reset team name\\
        teamNameTextField.setText("");
    }//GEN-LAST:event_clearButtonActionPerformed

    private void teamNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teamNameTextFieldActionPerformed
        String teamNameText = (String) teamNameTextField.getSelectedText();
    }//GEN-LAST:event_teamNameTextFieldActionPerformed

    private void oneTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_oneTextFieldFocusGained
        //an example format is present...when they click in the box go back to normal
        oneTextField.setText(""); 
        oneTextField.setForeground(Color.black);

    }//GEN-LAST:event_oneTextFieldFocusGained

    private void oneTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oneTextFieldActionPerformed

    private void twoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_twoTextFieldActionPerformed

    private void twoTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_twoTextFieldFocusGained
        twoTextField.setText("");
        twoTextField.setForeground(Color.black);
        threeTextField.setText("");
        threeTextField.setForeground(Color.black);
    }//GEN-LAST:event_twoTextFieldFocusGained

    private void teamNameTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_teamNameTextFieldFocusGained
        //it defaults to having the focus on the highest textfield on the frame!
    }//GEN-LAST:event_teamNameTextFieldFocusGained
////////////////////////////////////////////////////////////////////////////////
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LineupFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LineupFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LineupFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LineupFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new LineupFrame().setVisible(true);
                LineupFrame frame = new LineupFrame ();
                frame.setVisible(true);
                frame.setLocationRelativeTo(null); //center the frame 
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton clearButton;
    private javax.swing.JComboBox<String> eightComboBox;
    private javax.swing.JLabel eightLabel;
    private javax.swing.JTextField eightTextField;
    private javax.swing.JButton exitButton;
    private javax.swing.JComboBox<String> fiveComboBox;
    private javax.swing.JLabel fiveLabel;
    private javax.swing.JTextField fiveTextField;
    private javax.swing.JComboBox<String> fourComboBox;
    private javax.swing.JLabel fourLabel;
    private javax.swing.JTextField fourTextField;
    private javax.swing.JRadioButton homeButton;
    private javax.swing.JComboBox<String> nineComboBox;
    private javax.swing.JLabel nineLabel;
    private javax.swing.JTextField nineTextField;
    private javax.swing.JButton okButton;
    private javax.swing.JComboBox<String> oneComboBox;
    private javax.swing.JLabel oneLabel;
    private javax.swing.JTextField oneTextField;
    private javax.swing.JComboBox<String> sevenComboBox;
    private javax.swing.JLabel sevenLabel;
    private javax.swing.JTextField sevenTextField;
    private javax.swing.JComboBox<String> sixComboBox;
    private javax.swing.JLabel sixLabel;
    private javax.swing.JTextField sixTextField;
    private javax.swing.JPanel teamInformationPanel;
    private javax.swing.JLabel teamNameLabel;
    private javax.swing.JTextField teamNameTextField;
    private javax.swing.JComboBox<String> threeComboBox;
    private javax.swing.JLabel threeLabel;
    private javax.swing.JTextField threeTextField;
    private javax.swing.JComboBox<String> twoComboBox;
    private javax.swing.JLabel twoLabel;
    private javax.swing.JTextField twoTextField;
    private javax.swing.JRadioButton visitorButton;
    // End of variables declaration//GEN-END:variables
}
