/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Utilities.Customer;
import Utilities.getTxtData;
import Utilities.Validator;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;
import javax.swing.text.JTextComponent;
import javax.swing.text.NumberFormatter;

/**
 *
 * @author stahl
 */
public class CreditCardFrame extends javax.swing.JFrame {

    /**
     * Creates new form CreditCardFrame
     */
    public CreditCardFrame() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        visaPictureLabel = new javax.swing.JLabel();
        masterCardPictureLabel = new javax.swing.JLabel();
        discoverPictureLabel = new javax.swing.JLabel();
        creditCardNumberTextField = new javax.swing.JTextField();
        nameOnCardTextField = new javax.swing.JTextField();
        cvvTextField = new javax.swing.JTextField();
        amexPictureLabel = new javax.swing.JLabel();
        creditCardNumberLabel = new javax.swing.JLabel();
        expirationDateLabel = new javax.swing.JLabel();
        nameOnCardLabel = new javax.swing.JLabel();
        cvvLabel = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        expirationDateComboBoxMonth = new javax.swing.JComboBox<>();
        expirationDateComboBoxYear = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        creditCardNumberDisplayLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Secure Payment Window");
        setBackground(new java.awt.Color(102, 204, 255));

        visaPictureLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/visa.png"))); // NOI18N

        masterCardPictureLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/mastercard.png"))); // NOI18N

        discoverPictureLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/discover.png"))); // NOI18N

        creditCardNumberTextField.setForeground(new java.awt.Color(204, 204, 204));
        creditCardNumberTextField.setText("4654459909008981");
        creditCardNumberTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                creditCardNumberTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                creditCardNumberTextFieldFocusLost(evt);
            }
        });
        creditCardNumberTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                creditCardNumberTextFieldMouseClicked(evt);
            }
        });
        creditCardNumberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditCardNumberTextFieldActionPerformed(evt);
            }
        });
        creditCardNumberTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                creditCardNumberTextFieldKeyTyped(evt);
            }
        });

        nameOnCardTextField.setForeground(new java.awt.Color(204, 204, 204));
        nameOnCardTextField.setText("Steven Christopher Stahle");
        nameOnCardTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nameOnCardTextFieldMouseClicked(evt);
            }
        });

        cvvTextField.setForeground(new java.awt.Color(204, 204, 204));
        cvvTextField.setText("899");
        cvvTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cvvTextFieldMouseClicked(evt);
            }
        });
        cvvTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cvvTextFieldKeyTyped(evt);
            }
        });

        amexPictureLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/amex.png"))); // NOI18N

        creditCardNumberLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        creditCardNumberLabel.setText("Credit Card Number");

        expirationDateLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        expirationDateLabel.setText("Expiration Date");

        nameOnCardLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        nameOnCardLabel.setText("Name on Card");

        cvvLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cvvLabel.setText("CVV");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/secure_icon.png"))); // NOI18N
        jLabel9.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setText("Information Must Be Verified To Unlock Next Step in Checking Out");

        expirationDateComboBoxMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));

        expirationDateComboBoxYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035", "2036", " " }));

        jButton1.setText("loadFile");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        creditCardNumberDisplayLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        creditCardNumberDisplayLabel.setForeground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(amexPictureLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(discoverPictureLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(masterCardPictureLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(visaPictureLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(creditCardNumberLabel)
                            .addComponent(nameOnCardLabel)
                            .addComponent(expirationDateLabel)
                            .addComponent(cvvLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(expirationDateComboBoxMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(expirationDateComboBoxYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(cvvTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1)
                                .addGap(104, 104, 104))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(creditCardNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(creditCardNumberDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(nameOnCardTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 36, Short.MAX_VALUE))))))
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(creditCardNumberDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(creditCardNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(creditCardNumberLabel)))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(expirationDateLabel)
                    .addComponent(expirationDateComboBoxMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(expirationDateComboBoxYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameOnCardLabel)
                    .addComponent(nameOnCardTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cvvTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cvvLabel)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(amexPictureLabel)
                    .addComponent(discoverPictureLabel)
                    .addComponent(masterCardPictureLabel)
                    .addComponent(visaPictureLabel))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameOnCardTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameOnCardTextFieldMouseClicked
        int counter = 1; //this lets the data already entered be kept in the field so they dont have to type it again 
        if(!(counter >1))
        {
            nameOnCardTextField.setText("");
            nameOnCardTextField.setForeground(null);
        }
    }//GEN-LAST:event_nameOnCardTextFieldMouseClicked

    private void cvvTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cvvTextFieldMouseClicked
        int counter = 1;
        if(!(counter >1))
        {
            cvvTextField.setText("");
            cvvTextField.setForeground(null);
        }
    }//GEN-LAST:event_cvvTextFieldMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        getTxtData i = new getTxtData();
        i.loadData();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void creditCardNumberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditCardNumberTextFieldActionPerformed

    }//GEN-LAST:event_creditCardNumberTextFieldActionPerformed

    private void creditCardNumberTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_creditCardNumberTextFieldMouseClicked
        int counter = 1;
        if(!(counter >1))
        {
            creditCardNumberTextField.setText(""); //this resizes it if u accidentally click out tho
            creditCardNumberTextField.setForeground(null);//null means black; default
        }
    }//GEN-LAST:event_creditCardNumberTextFieldMouseClicked

    private void creditCardNumberTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_creditCardNumberTextFieldFocusGained

    }//GEN-LAST:event_creditCardNumberTextFieldFocusGained

    private void creditCardNumberTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_creditCardNumberTextFieldKeyTyped
        char c = evt.getKeyChar(); //get the key they pressed
        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)) {
            getToolkit().beep();
            evt.consume();
        }
        
    }//GEN-LAST:event_creditCardNumberTextFieldKeyTyped

    private void cvvTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cvvTextFieldKeyTyped
        char c = evt.getKeyChar(); //get the key they pressed
        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_cvvTextFieldKeyTyped

    private void creditCardNumberTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_creditCardNumberTextFieldFocusLost
        int counter = 1;
        String holder = creditCardNumberTextField.getText();
        Validator v = new Validator();
        //were gonna check if they entered 15 or 16 digits 
        if(!v.hasFifteenOrSixteenDigits(creditCardNumberTextField, "credit card number "))
        {
           creditCardNumberDisplayLabel.setText("Your CC needs the right amount of digits.");
        }
        String creditCardType = v.isValidCreditCardNum(creditCardNumberTextField, "credit card ");
        if(creditCardType != "" || creditCardType != null)
        {
            creditCardNumberDisplayLabel.setText("");
            creditCardNumberTextField.setForeground(new Color(102, 204, 0));
        }
        Border border = LineBorder.createBlackLineBorder();
        if(creditCardType == "Visa"){visaPictureLabel.setBorder(border);}
        if(creditCardType == "MasterCard"){masterCardPictureLabel.setBorder(border);}
        if(creditCardType == "American Express"){amexPictureLabel.setBorder(border);}
        if(creditCardType == "Discover"){discoverPictureLabel.setBorder(border);}
            
        
        //were gonna tell them they're type of cc 
    }//GEN-LAST:event_creditCardNumberTextFieldFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreditCardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreditCardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreditCardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreditCardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new CreditCardFrame().setVisible(true);
                CreditCardFrame frame = new CreditCardFrame();
                frame.setVisible(true);
                frame.setLocationRelativeTo(null); //center the frame 
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amexPictureLabel;
    private javax.swing.JLabel creditCardNumberDisplayLabel;
    private javax.swing.JLabel creditCardNumberLabel;
    private javax.swing.JTextField creditCardNumberTextField;
    private javax.swing.JLabel cvvLabel;
    private javax.swing.JTextField cvvTextField;
    private javax.swing.JLabel discoverPictureLabel;
    private javax.swing.JComboBox<String> expirationDateComboBoxMonth;
    private javax.swing.JComboBox<String> expirationDateComboBoxYear;
    private javax.swing.JLabel expirationDateLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel masterCardPictureLabel;
    private javax.swing.JLabel nameOnCardLabel;
    private javax.swing.JTextField nameOnCardTextField;
    private javax.swing.JLabel visaPictureLabel;
    // End of variables declaration//GEN-END:variables
}
